# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 964dfc965862690bd1575f8b8b4ae33f4aa88251dd642cc00173a0de0936879b78cdd142c6478602b8576b597b143e99c1c30522d1d18ff2af1a172b93c448b2
  github_token: '11005adaae560e71aa50c2ba4124e945c38f3f93'
  github_app_id: '651692db8ef2d40913ff'
  github_app_secret: '85a54d91e1d436483930b0e00d3b21de73c6b016'

test:
  secret_key_base: 9aaf264a8c9fe9d98e2892ae1adb8a46e294fd433f06b0230b3f1eece45761bdcb0e1abb37d8949ddb82e4b6a0eb46fc19960be8fb22893f2cfacfd3cd351694
  github_token: '11005adaae560e71aa50c2ba4124e945c38f3f93'
  github_app_id: '651692db8ef2d40913ff'
  github_app_secret: '85a54d91e1d436483930b0e00d3b21de73c6b016'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_token: #prod#
  github_app_id: #prod#
  github_app_secret: #prod#
